#server.port=8082
spring:
  elasticsearch:
    rest:
      uris: http://47.113.202.84:9200
      connection-timeout: 100s

#  datasource:
#    druid:
#      url: jdbc:mysql://localhost:3306/project_fmmall?characterEncoding=utf-8&serverTimezone=UTC  #\u672C\u5730
#      #      url: jdbc:mysql://47.113.202.84:3306/project_fmmall?characterEncoding=utf-8&serverTimezone=UTC   #\u8FDC\u7A0B
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: 123456  #your_password
#  redis:
#    host: 47.113.202.84
#    password: Smbo1IhcaF9YEJvZ
#    port: 6379
#    database: 0
#mybatis:
#  mapper-locations: classpath:mappers/*.xml
#  type-aliases-package: com.xiaojiang.fmmall.entity
#logging:
#  level:
#    io.swagger.models.parameters.AbstractSerializableParameter: error
#redisson:
#  addr:
#    singleAddr:
#      host: redis://47.113.202.84:6379
#      password: Smbo1IhcaF9YEJvZ
#      database: 0